### ISSUE TITLE
Does enumerated elements really requires minLength and maxLength?

### ISSUE THREAD

**Issue by NandaBalakrishnan** [xlate/staedi#341] opened 2023-03-28 07:25 UTC
getting Data element too long for enumerated elements if the min and max length is not provided. even in ansi standard it is not there?
why staedi throwing error for enumerated values?
where we will get min and max length for enumerated values?

**Comment by MikeEdgar** [comment] 2023-03-28 16:15
Please attach the segment or some code. That error means `writeEndSegment` was called on the writer with missing elements or something was too short.

**Comment by NandaBalakrishnan** [comment] 2023-03-28 16:31
throw new EDIStreamException("Invalid X12 ISA segment: too short or elements missing");
no error code thrown

**Comment by MikeEdgar** [comment] 2023-03-28 16:35
It looks like your code is calling `writeEndSegment` before all of the `ISA` elements have been written or the elements are too short. The elements will be padded automatically if you set `EDIOutputFactory.FORMAT_ELEMENTS` to `true` on the EDIOutputFactory before creating the writer.

**Comment by NandaBalakrishnan** [comment] 2023-03-28 16:58
no sir, i am calling writeEndsegment after writing all elements only.

**Comment by MikeEdgar** [comment] 2023-03-28 17:00
Would you be able to attach a small reproducer project that I can look at?

**Comment by NandaBalakrishnan** [comment] 2023-03-28 17:27
sure Sir, what will be possible values for      
        public static final String SEGMENT = "io.xlate.edi.stream.delim.segment";

**Comment by MikeEdgar** [comment] 2023-03-28 17:29
It depends on the input, the segment delimiter is read from your input file.

**Comment by NandaBalakrishnan** [comment] 2023-03-28 17:37
sample EDI file, here segment terminator is '\n', while generating ack, it is throwing above error
`ISA*00*`          *00*          *02*RRRR           *02*00888888      *220128*0750*U*00301*000111112*0*T*>
GS*MM*RRRR*00888888*20220128*0750*122222*X*003010
ST*210*0001
SE*2*0001
GE*1*122222
IEA*1*000111112

`

**Comment by MikeEdgar** [comment] 2023-03-28 17:40
It's tough to say without seeing how your code is interacting with the `EDIStreamWriter`. Can you provide a sample program that has the issue?

**Comment by MikeEdgar** [comment] 2023-04-03 10:57
Closing as the discussion on `EDIStreamException: Invalid X12 ISA segment: too short or elements missing` will continue in #323

**Closed by MikeEdgar** 2023-04-03 10:57 UTC
